### PR TITLE
Rebasing v3 to master

### PR DESCRIPTION
**Pull request by aphelionz**
This PR is an attempt to rebase master against v3 so that v3 can eventually be merged into master. Since there were recent features added to both `v3` and `master`, please pay particular attention to `social-nfts` and `social-bridge` while reviewing.

Sorry that it's such a massive PR :(

### CODE REVIEW

**Comment by aphelionz** [comment]
This is as far as I got, looks like we need to wire up the `timestamp` pallet for testing, via `cargo test`

```
error[E0277]: the trait bound `Test: pallet_timestamp::pallet::Config` is not satisfied
   --> frame/social-bridge/src/mock.rs:131:6
    |
131 | impl pallet_social_nft::Config for Test {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `pallet_timestamp::pallet::Config` is not implemented for `Test`
    |
   ::: /home/mark/Documents/Projects/SocialNetwork/blockchain/frame/social-nft/src/lib.rs:39:60
    |
39  | pub trait Config: system::Config + pallet_assets::Config + pallet_timestamp::Config {
    |                                                            ------------------------ required by this bound in `pallet_social_nft::Config`

error[E0277]: the trait bound `Test: pallet_timestamp::pallet::Config` is not satisfied
   --> frame/social-bridge/src/mock.rs:136:6
    |
136 | impl Config for Test {
    |      ^^^^^^ the trait `pallet_timestamp::pallet::Config` is not implemented for `Test`
    |
   ::: frame/social-bridge/src/lib.rs:22:11
    |
22  | pub trait Config:
    |           ------ required by a bound in this
23  |     system::Config + bridge::Config + pallet_assets::Config + pallet_social_nft::Config
    |                                                               ------------------------- required by this bound in `Config`
```

**Comment by regenaissance** [comment]
Uhh let's not do this, can't we just cherry pick the social-nft stuff into this branch?

**Comment by aphelionz** [comment]
We can try, there's quite a few commits to master in addition to that. Totally open to other ideas here though

**Comment by andor0** [comment]
imho, do so is simpler:
1. merge the `master` branch to the `v3` branch
2. remove the `master` branch
3. do the `v3` branch a new `master` branch

so it will be less diff https://github.com/social-network/blockchain/compare/v3...master

**Pull request closed without merging**
